module ElasticGraph
  module Apollo
    module GraphQL
      class ServiceFieldResolver
        include ::ElasticGraph::_GraphQLResolverWithoutLookahead

        private

        def service_sdl: (ElasticGraph::GraphQL::Schema) -> ::String
      end
    end
  end
end
