module ElasticGraph
  module SchemaDefinition
    module SchemaElements
      class GraphQLSDLEnumerator
        include ::Enumerable[::String]
        attr_reader schema_def_state: State

        def initialize: (State, ::Array[graphQLType]) -> void
        def each: () { (String) -> void } -> void

        private

        @schema_def_state: State
        @all_types: ::Array[graphQLType]
      end
    end
  end
end
