module ElasticGraph
  module Support
    module Logger
      extend _BuildableFromParsedYaml[::Logger]

      module Factory
        def self.build: (config: Config, ?device: ::Logger::logdev?) -> ::Logger
      end

      class JSONAwareFormatter
        include ::Logger::_Formatter
        @original_formatter: ::Logger::Formatter

        # Steep 1.6 complains about our impl returning `nil` unless we define this as void
        def initialize: () -> void
      end

      class ConfigSupertype
        extend Support::Config::ClassMethods[Config]

        attr_reader level: ::String
        attr_reader device: ::String
        attr_reader formatter: ::Logger::_Formatter

        def initialize: (
          ?level: ::String,
          ?device: ::String,
          ?formatter: ::String
        ) -> void

        def with: (
          ?level: ::String,
          ?device: ::String,
          ?formatter: ::Logger::_Formatter
        ) -> Config

        def self.members: () -> ::Array[::Symbol]
      end

      class Config < ConfigSupertype
        def prepared_device: () -> (::String | ::IO)
        def self.from_parsed_yaml: (::Hash[::String, untyped]) -> Config

        private

        def convert_values: (formatter: ::String, level: ::String, device: ::String) -> ::Hash[::Symbol, untyped]
      end
    end
  end
end
