module ElasticGraph
  module SchemaArtifacts
    class FromDiskSupertype
      attr_reader artifacts_dir: ::String
      def initialize: (artifacs_dir: ::String) -> void
    end

    class FromDisk < FromDiskSupertype
      include _SchemaArtifacts
      include ArtifactsHelperMethods

      def self.new:
        (artifacs_dir: ::String) -> instance
      | (::String) -> instance

      private

      @graphql_schema_string: ::String?
      @datastore_config: ::Hash[::String, untyped]?
      @runtime_metadata: SchemaArtifacts::RuntimeMetadata::Schema?
      @available_json_schema_versions: ::Set[::Integer]?
      @latest_json_schema_version: ::Integer?

      def read_artifact: (::String) -> ::String
      def parsed_yaml_from: (::String) -> ::Hash[::String, untyped]

      @json_schemas_by_version: ::Hash[::Integer, ::Hash[::String, untyped]]
      def json_schemas_by_version: () -> ::Hash[::Integer, ::Hash[::String, untyped]]

      def load_json_schema: (::Integer) -> ::Hash[::String, untyped]
    end
  end
end
