# Copyright 2024 - 2025 Block, Inc.
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.
#
# frozen_string_literal: true

source "https://rubygems.org"

gem "gem-release", "~> 2.2"
gem "nokogiri", "~> 1.18", ">= 1.18.9"
gem "rake", "~> 13.3"
gem "redcarpet", "~> 3.6", ">= 3.6.1"
gem "yard", "~> 0.9", ">= 0.9.37"
gem "yard-markdown", "~> 0.5"
