module JSONSchemer
  type error = {
    "data" => untyped,
    "data_pointer" => ::String,
    "schema" => ::Hash[::String, untyped],
    "schema_pointer" => ::String,
    "root_schema" => ::Hash[::String, untyped],
    "type" => ::String,
    "details" => untyped?
  }

  module Draft7
    SCHEMA: ::Hash[::String, untyped]
  end

  class Schema
    attr_reader value: ::Hash[::String, untyped]
    attr_reader configuration: Configuration
    def ref: (::String) -> Schema
    def valid?: (::Hash[::String | ::Symbol, untyped]) -> bool
    def validate: (::Hash[::String | ::Symbol, untyped]) -> ::Enumerator[error, error]
  end

  def self.schema: (
    ::Hash[::String | ::Symbol, untyped],
    ?configuration: Configuration,
    ?meta_schema: ::String,
    ?regexp_resolver: "ruby" | "ecma"
  ) -> Schema

  class Configuration
    attr_accessor insert_property_defaults: bool
  end
end
