module ElasticGraph
  module QueryRegistry
    module GraphQLExtension: GraphQL
    end

    class RegistryAwareQueryExecutor < GraphQL::QueryExecutor
      def initialize: (
        registry_directory: ::String,
        allow_unregistered_clients: bool,
        allow_any_query_for_clients: ::Array[::String],
        schema: GraphQL::Schema,
        monotonic_clock: Support::MonotonicClock,
        logger: ::Logger,
        slow_query_threshold_ms: ::Integer
      ) -> void

      private

      @registry: Registry
    end
  end
end
