# Copyright 2024 - 2025 Block, Inc.
#
# Use of this source code is governed by an MIT-style
# license that can be found in the LICENSE file or at
# https://opensource.org/licenses/MIT.
#
# frozen_string_literal: true

class MermaidSnippetValidator < SnippetValidator
  def validate(snippet)
    ValidationResult.skipped("Mermaid diagram validation skipped (automatically generated by `script/update_dependency_diagrams`)")
  end
end
